'use client';
import StagesOrder from '@/shared/Order/components/stages/StagesOrder';
import { Metadata } from 'next';
import styledProcess from '@/styles/PagesModules/order/Process.module.scss';
import { usePathname } from 'next/navigation';

// export const metadata: Metadata = {
//     title: 'Address',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const currentPath = usePathname();
    const stages = {
        ADDRESS: '/order/process',
        DELIVERY: '/order/process/delivery',
        PAYMENT: '/order/process/payment',
    };

    return (
        <div>
            <div className={`${styledProcess.stages} dfj container`}>
                <StagesOrder stages='payment' isTheStage={currentPath === stages.ADDRESS} />
                <StagesOrder stages='shipping' isTheStage={currentPath === stages.DELIVERY} />
                <StagesOrder stages='payment' isTheStage={currentPath === stages.PAYMENT} />
            </div>
            {children}
        </div>
    );
}
